### ISSUE TITLE
Issue loading Shell Element Models

### ISSUE THREAD

**Issue by johonea4** [pyansys/DPF-Post#25]
Hello. I'm having an issue when loading RST files with dpf post, and I believe the issue persists in dpf-core as well. When loading a verification test case RST file generated from Ansys 19 (Have checked prior versions with similar behavior) parts of the model are missing when doing a mesh.plot(). Below are images of what I'm expecting vs. what I get. Any insight? I am able to share the RST as well if wanted.

![image](https://user-images.githubusercontent.com/40772230/128420695-fa7b3f72-9182-4736-a054-775b1584e480.png)
^^^ Generated from reading RST with in-house C/C++ reader

![image](https://user-images.githubusercontent.com/40772230/128420868-b8b7a0b6-6573-4a4b-8e1d-233065f5052c.png)
^^^ DPF Post mesh.plot result

**Comment by johonea4** [comment]
Additional Info: I opened the same file with the legacy ansys-mapdl-reader and the plotted result matches expectation (1st image above). I haven't been able to find any cause of why dpf-post is producing the 2nd image above. I will also mention that the node counts match in all readers, but dpf-post's element count is reduced by the number of missing elements. It's strange.

**Comment by rlagha** [comment]
Hi @johonea4 , Thanks for finding this, please could you share the rst file?
Thanks
Ramdane

**Comment by johonea4** [comment]
[v190.zip](https://github.com/pyansys/DPF-Post/files/6955116/v190.zip)

Here are 2 sets of RST/CDB files this happens on.

**Comment by anslpa** [comment]
Hi @johonea4, 
The issue was that the shell43 and shell63 elements (used in the provided file) were not supported. A fix is found and will be available for the next Ansys 2022 R1 release. @rlagha 
Thank you.
