### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by pmaroneh** [pyansys/DPF-Post#26]
There seems to be some typos in the "Structural Temperature" section of this page: https://postdocs.pyansys.com/user_guide/accessing_results.html#structural-temperature

It is mentioned that the elastic strain object object and the displacement result are instantiated, and that the xy elastic strain data is obtained, but what we are actually getting here is the scalar value of the temperature:

![image](https://user-images.githubusercontent.com/76440649/129209141-f0c6b7d7-09db-47e3-a7af-77817ce82d77.png)

**Comment by anslpa** [comment]
Hi @pmaroneh, thank you for notifying. 
PR #27 is fixing this. Once it is merged, the documentation will have to be released before the changes are taken into account.
